# Generated by Django 5.2.8 on 2025-11-27 00:16

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(upload_to=core.models.safe_image_path),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location_found',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
