# Generated by Django 5.2.8 on 2025-11-26 01:27

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='found_by',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='location_found',
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='date_found',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.safe_image_path),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
