# Generated by Django 5.2.8 on 2025-11-26 01:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_remove_lostitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(default='FOUND', max_length=20),
        ),
    ]
