# Generated by Django 5.2.8 on 2025-11-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lostitem_created_at_alter_lostitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
